# Generated by Django 4.1.2 on 2022-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20221007_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
