# Generated by Django 4.1.2 on 2022-10-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileModel",
        ),
    ]
